BEGIN;

-- Daily report lifecycle
ALTER TABLE public.daily_reports
  ADD COLUMN status text NOT NULL DEFAULT 'draft',
  ADD COLUMN updated_at timestamp with time zone NOT NULL DEFAULT now();

ALTER TABLE public.daily_reports
  ALTER COLUMN published_at DROP DEFAULT;

UPDATE public.daily_reports
SET
  status = CASE
    WHEN published_at IS NULL THEN 'draft'
    ELSE 'published'
  END,
  updated_at = now();

UPDATE public.daily_reports
SET is_premium = false
WHERE is_premium IS NULL;

UPDATE public.daily_reports
SET created_at = now()
WHERE created_at IS NULL;

UPDATE public.daily_reports
SET cover_image_url = NULL
WHERE btrim(cover_image_url) = '';

ALTER TABLE public.daily_reports
  ALTER COLUMN cover_image_url DROP DEFAULT,
  ALTER COLUMN is_premium SET DEFAULT false,
  ALTER COLUMN is_premium SET NOT NULL,
  ALTER COLUMN created_at SET DEFAULT now(),
  ALTER COLUMN created_at SET NOT NULL,
  ADD CONSTRAINT daily_reports_status_check
    CHECK (status IN ('draft', 'published', 'archived')),
  ADD CONSTRAINT daily_reports_publish_state_check
    CHECK (
      (status = 'draft' AND published_at IS NULL)
      OR
      (
        status IN ('published', 'archived')
        AND published_at IS NOT NULL
      )
    );

DROP INDEX public.idx_reports_published_at;

CREATE INDEX idx_daily_reports_published_feed
  ON public.daily_reports (published_at DESC, id DESC)
  WHERE status = 'published';

CREATE INDEX idx_daily_reports_author_created_at
  ON public.daily_reports (author_id, created_at DESC);

CREATE INDEX idx_report_symbols_symbol_id
  ON public.report_symbols (symbol_id);

-- A report item is an editorial news unit inside one daily report.
CREATE TABLE public.daily_report_items (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id  integer                  NOT NULL,
  position   integer                  NOT NULL,
  headline   character varying(500)   NOT NULL,
  body       text                     NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT daily_report_items_report_id_fkey
    FOREIGN KEY (report_id)
    REFERENCES public.daily_reports(id)
    ON DELETE CASCADE,
  CONSTRAINT daily_report_items_position_check
    CHECK (position > 0),
  CONSTRAINT daily_report_items_headline_check
    CHECK (btrim(headline) <> ''),
  CONSTRAINT daily_report_items_body_check
    CHECK (btrim(body) <> ''),
  CONSTRAINT daily_report_items_report_position_key
    UNIQUE (report_id, position)
);

-- A news source represents an actual external article or document, not a fixed website.
CREATE TABLE public.news_sources (
  id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url                 text                     NOT NULL,
  title               text,
  publisher_name      text,
  source_published_at timestamp with time zone,
  created_at          timestamp with time zone NOT NULL DEFAULT now(),
  updated_at          timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT news_sources_url_check
    CHECK (btrim(url) <> ''),
  CONSTRAINT news_sources_url_key
    UNIQUE (url)
);

-- Sources are reusable and ordered independently for each report item.
CREATE TABLE public.report_item_sources (
  report_item_id integer                  NOT NULL,
  source_id      integer                  NOT NULL,
  position       integer                  NOT NULL,
  created_at     timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT report_item_sources_pkey
    PRIMARY KEY (report_item_id, source_id),
  CONSTRAINT report_item_sources_report_item_id_fkey
    FOREIGN KEY (report_item_id)
    REFERENCES public.daily_report_items(id)
    ON DELETE CASCADE,
  CONSTRAINT report_item_sources_source_id_fkey
    FOREIGN KEY (source_id)
    REFERENCES public.news_sources(id)
    ON DELETE RESTRICT,
  CONSTRAINT report_item_sources_position_check
    CHECK (position > 0),
  CONSTRAINT report_item_sources_item_position_key
    UNIQUE (report_item_id, position)
);

CREATE INDEX idx_report_item_sources_source_id
  ON public.report_item_sources (source_id);

-- Keep updated_at consistent for mutable report records.
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.set_updated_at() FROM PUBLIC, anon, authenticated;

CREATE TRIGGER daily_reports_set_updated_at
BEFORE UPDATE ON public.daily_reports
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER daily_report_items_set_updated_at
BEFORE UPDATE ON public.daily_report_items
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER news_sources_set_updated_at
BEFORE UPDATE ON public.news_sources
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

-- Publication is the only supported transition from draft to published.
CREATE OR REPLACE FUNCTION public.publish_daily_report(p_report_id integer)
RETURNS public.daily_reports
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_report public.daily_reports;
BEGIN
  SELECT *
  INTO v_report
  FROM public.daily_reports
  WHERE id = p_report_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'daily report % does not exist', p_report_id
      USING ERRCODE = 'P0002';
  END IF;

  IF v_report.status <> 'draft' THEN
    RAISE EXCEPTION 'daily report % is not a draft', p_report_id
      USING ERRCODE = 'P0001';
  END IF;

  IF btrim(v_report.title) = ''
     OR btrim(v_report.summary) = ''
     OR btrim(v_report.content) = '' THEN
    RAISE EXCEPTION 'daily report % has incomplete report content', p_report_id
      USING ERRCODE = '23514';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.daily_report_items
    WHERE report_id = p_report_id
  ) THEN
    RAISE EXCEPTION 'daily report % requires at least one item', p_report_id
      USING ERRCODE = '23514';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.daily_report_items AS item
    WHERE item.report_id = p_report_id
      AND NOT EXISTS (
        SELECT 1
        FROM public.report_item_sources AS item_source
        WHERE item_source.report_item_id = item.id
      )
  ) THEN
    RAISE EXCEPTION 'every item in daily report % requires at least one source', p_report_id
      USING ERRCODE = '23514';
  END IF;

  UPDATE public.daily_reports
  SET
    status = 'published',
    published_at = now()
  WHERE id = p_report_id
  RETURNING * INTO v_report;

  RETURN v_report;
END;
$$;

CREATE OR REPLACE FUNCTION public.archive_daily_report(p_report_id integer)
RETURNS public.daily_reports
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_report public.daily_reports;
BEGIN
  UPDATE public.daily_reports
  SET status = 'archived'
  WHERE id = p_report_id
    AND status = 'published'
  RETURNING * INTO v_report;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'daily report % is not published or does not exist', p_report_id
      USING ERRCODE = 'P0001';
  END IF;

  RETURN v_report;
END;
$$;

CREATE OR REPLACE FUNCTION public.delete_daily_report_draft(p_report_id integer)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  DELETE FROM public.daily_reports
  WHERE id = p_report_id
    AND status = 'draft';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'daily report % is not a draft or does not exist', p_report_id
      USING ERRCODE = 'P0001';
  END IF;
END;
$$;

REVOKE ALL ON FUNCTION public.publish_daily_report(integer) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.archive_daily_report(integer) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.delete_daily_report_draft(integer) FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.publish_daily_report(integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.archive_daily_report(integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.delete_daily_report_draft(integer) TO service_role;

-- Public clients can read only rows that belong to a currently published report.
ALTER TABLE public.daily_report_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.news_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.report_item_sources ENABLE ROW LEVEL SECURITY;

CREATE POLICY daily_reports_public_read
ON public.daily_reports
FOR SELECT
TO anon, authenticated
USING (status = 'published' AND published_at IS NOT NULL);

CREATE POLICY daily_report_items_public_read
ON public.daily_report_items
FOR SELECT
TO anon, authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.daily_reports AS report
    WHERE report.id = daily_report_items.report_id
      AND report.status = 'published'
      AND report.published_at IS NOT NULL
  )
);

CREATE POLICY report_item_sources_public_read
ON public.report_item_sources
FOR SELECT
TO anon, authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.daily_report_items AS item
    JOIN public.daily_reports AS report
      ON report.id = item.report_id
    WHERE item.id = report_item_sources.report_item_id
      AND report.status = 'published'
      AND report.published_at IS NOT NULL
  )
);

CREATE POLICY news_sources_public_read
ON public.news_sources
FOR SELECT
TO anon, authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.report_item_sources AS item_source
    JOIN public.daily_report_items AS item
      ON item.id = item_source.report_item_id
    JOIN public.daily_reports AS report
      ON report.id = item.report_id
    WHERE item_source.source_id = news_sources.id
      AND report.status = 'published'
      AND report.published_at IS NOT NULL
  )
);

CREATE POLICY report_symbols_public_read
ON public.report_symbols
FOR SELECT
TO anon, authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.daily_reports AS report
    WHERE report.id = report_symbols.report_id
      AND report.status = 'published'
      AND report.published_at IS NOT NULL
  )
);

-- Browser clients are read-only. Administrative writes go through the backend.
REVOKE INSERT, UPDATE, DELETE ON public.daily_reports FROM anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.report_symbols FROM anon, authenticated;
REVOKE ALL ON public.daily_report_items FROM anon, authenticated;
REVOKE ALL ON public.news_sources FROM anon, authenticated;
REVOKE ALL ON public.report_item_sources FROM anon, authenticated;

GRANT SELECT ON public.daily_report_items TO anon, authenticated;
GRANT SELECT ON public.news_sources TO anon, authenticated;
GRANT SELECT ON public.report_item_sources TO anon, authenticated;

REVOKE ALL ON SEQUENCE public.daily_report_items_id_seq FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.news_sources_id_seq FROM anon, authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.daily_report_items TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.news_sources TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.report_item_sources TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.daily_report_items_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.news_sources_id_seq TO service_role;

-- Published and archived reports must be removed through lifecycle operations.
REVOKE DELETE ON public.daily_reports FROM service_role;

COMMIT;
